### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by konkers** [karlcswanson/CatPatch#1]
Hi, I found this project while looking for a NE8FDV kicad footprint.  I'd love to use yours for my project but don't see any license terms stated for this project.  Would be great if you could add one!

**Comment by karlcswanson** [comment]
Thanks for checking! I think I looked into adding in a license earlier but couldn't figure out the best route to take on the hardware side of things with monorepo that contains a project & libraries.

Just licensed as MIT. Hope that works for you (and KiCad).
